### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by sunsetsurfer9** [yujunhuics/LayoutReader#2]
你好，请问代码经常报错 “The size of tensor a (11) must match the size of tensor b (9) at non-singleton dimension 1”是输入有问题吗？示例输入如下：
[[ 91 128 713 488]
 [ 93 141 247 353]
 [ 94 546 386 959]
 [ 94 115 174 125]
 [ 94 141 246 349]
 [370 493 658 508]
 [414 546 706 959]
 [654 986 706 998]
 [654 986 706 998]]
Traceback (most recent call last):
  File "/home/aistudio/LayoutReader/predict.py", line 93, in <module>
    order = layoutreader(bboxes1)
  File "/home/aistudio/LayoutReader/predict.py", line 46, in layoutreader
    logits = model(**inputs).logits.cpu().squeeze(0)
  File "/home/aistudio/ENV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/aistudio/ENV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/aistudio/LayoutReader/model.py", line 58, in forward
    outputs = self.layoutlmv3(
  File "/home/aistudio/ENV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/aistudio/ENV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/aistudio/ENV/lib/python3.10/site-packages/transformers/models/layoutlmv3/modeling_layoutlmv3.py", line 907, in forward
    embedding_output = self.embeddings(
  File "/home/aistudio/ENV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/aistudio/ENV/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/aistudio/ENV/lib/python3.10/site-packages/transformers/models/layoutlmv3/modeling_layoutlmv3.py", line 346, in forward
    embeddings = embeddings + spatial_position_embeddings
RuntimeError: The size of tensor a (11) must match the size of tensor b (9) at non-singleton dimension 1

**Comment by sunsetsurfer9** [comment]
找到原因了，输入用np.array会报上述错误，应该输入list，不好意思。
